# This workflow will run tests using node and then publish a package to GitHub Packages when a release is created
# For more information see: https://docs.github.com/en/actions/publishing-packages/publishing-nodejs-packages

name: Node.js Build and test

on:
  workflow_dispatch

jobs:
  build:
    runs-on: ubuntu-latest
#    steps:
#      - uses: actions/checkout@v3
#      - uses: actions/setup-node@v3
#        with:
#          repo-token: ${{ secrets.GITHUB_TOKEN }}
#          node-version: 16
#      - run: npm ci
#      - run: npm test

    steps:
    - uses: actions/checkout@v4
    - name: Use Node.js
      uses: actions/setup-node@v3
      with:
        always-auth: true
        node-version: '20.x'
        registry-url: https://npm.pkg.github.com
        scope: '@featurefree'
    - name: Install dependencies
      run: npm ci
      env:
        NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
